/**
 * Audit & Notification Service
 * Centralized service to create audit logs and notifications for all actions
 */

import API from './api.service';
import { createDirectNotification, createDirectAuditLog } from './direct-supabase-notification.service';

export interface AuditLogData {
  userId: string;
  userRole: 'customer' | 'barber' | 'admin' | 'system';
  userName?: string;
  userEmail?: string;
  action: string;
  entityType?: string;
  entityId?: string;
  description: string; // Keep for backwards compatibility, will be mapped to details
  status: 'success' | 'error' | 'warning';
  metadata?: Record<string, any>;
  // ❌ Removed for privacy: ipAddress and userAgent
}

export interface NotificationData {
  userId: string;
  userRole: 'customer' | 'barber' | 'admin';
  type: string;
  title: string;
  message: string;
  relatedId?: string;
  relatedType?: string;
  actionUrl?: string;
  actionLabel?: string;
}

/**
 * Create an audit log entry
 */
export async function createAuditLog(data: AuditLogData): Promise<void> {
  try {
   
    await API.auditLogs.create({
      userId: data.userId,
      userRole: data.userRole,
      userName: data.userName,
      userEmail: data.userEmail,
      action: data.action,
      entityType: data.entityType,
      entityId: data.entityId,
      // Map description to details JSONB field (new schema)
      details: {
        description: data.description,
        ...data.metadata
      },
      status: data.status,
      // ❌ No IP address or user agent for privacy!
      // createdAt is auto-generated by the database
    });
   
  } catch (error) {
    console.error('❌ Failed to create audit log:', error);
    // Don't throw - audit logs are optional
  }
}

/**
 * Create a notification
 */
export async function createNotification(data: NotificationData): Promise<void> {
  try {
    console.log('📤 Creating notification:', data);
    
    // Try direct Supabase first to ensure it reaches the database
    try {
      await createDirectNotification({
        user_id: data.userId,
        user_role: data.userRole,
        type: data.type,
        title: data.title,
        message: data.message,
        related_id: data.relatedId,
        related_type: data.relatedType,
        action_url: data.actionUrl,
        action_label: data.actionLabel,
      });
      console.log('✅ Notification sent via direct Supabase');
    } catch (directError) {
      console.error('⚠️ Direct Supabase notification failed, trying API fallback:', directError);
      
      // Fallback to API service
      await API.notifications.create({
        userId: data.userId,
        userRole: data.userRole,
        type: data.type,
        title: data.title,
        message: data.message,
        relatedId: data.relatedId,
        relatedType: data.relatedType,
        actionUrl: data.actionUrl,
        actionLabel: data.actionLabel,
        isRead: false,
      });
      console.log('✅ Notification sent via API fallback');
    }
  } catch (error) {
    console.error('❌ Failed to create notification:', error);
    // Don't throw - notifications are optional
  }
}

/**
 * Log appointment creation
 */
export async function logAppointmentCreated(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string,
  appointmentId: string,
  appointmentDetails: {
    service: string;
    barber: string;
    barberId: string;
    date: string;
    time: string;
    price: number;
  }
): Promise<void> {
  // Create audit log
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'appointment_created',
    entityType: 'appointment',
    entityId: appointmentId,
    description: `${userName} created appointment for ${appointmentDetails.service} with ${appointmentDetails.barber} on ${appointmentDetails.date} at ${appointmentDetails.time}`,
    status: 'success',
    metadata: appointmentDetails,
  });

  // Create notification for admin
  await createNotification({
    userId: 'admin', // Will be sent to all admins
    userRole: 'admin',
    type: 'appointment_created',
    title: 'New Appointment Created',
    message: `${userName} booked ${appointmentDetails.service} with ${appointmentDetails.barber} on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });

  // Create notification for barber
  await createNotification({
    userId: appointmentDetails.barberId,
    userRole: 'barber',
    type: 'appointment_assigned',
    title: 'New Appointment Assigned',
    message: `${userName} booked ${appointmentDetails.service} on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });

  // Create confirmation notification for customer
  await createNotification({
    userId,
    userRole: 'customer',
    type: 'appointment_booked',
    title: '✅ Booking Confirmed',
    message: `Your appointment for ${appointmentDetails.service} with ${appointmentDetails.barber} on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time} has been submitted. Please complete payment to confirm.`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: `/appointments?highlight=${appointmentId}`,
    actionLabel: 'View Booking',
  });
}

/**
 * Log appointment status update
 */
export async function logAppointmentStatusUpdate(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string,
  appointmentId: string,
  oldStatus: string,
  newStatus: string,
  appointmentDetails: {
    customerId: string;
    customerName: string;
    barberId: string;
    service: string;
    date: string;
    time: string;
  }
): Promise<void> {
  // Create audit log
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: `appointment_${newStatus}`,
    entityType: 'appointment',
    entityId: appointmentId,
    description: `${userName} changed appointment status from ${oldStatus} to ${newStatus}`,
    status: 'success',
    metadata: {
      oldStatus,
      newStatus,
      ...appointmentDetails,
    },
  });

  // Create notification for customer
  const customerMessages: Record<string, string> = {
    confirmed: `Your appointment for ${appointmentDetails.service} on ${new Date(appointmentDetails.date).toLocaleDateString()} has been confirmed!`,
    completed: `Your appointment for ${appointmentDetails.service} has been completed. Please leave a review!`,
    cancelled: `Your appointment for ${appointmentDetails.service} on ${new Date(appointmentDetails.date).toLocaleDateString()} has been cancelled.`,
    rejected: `Your appointment request for ${appointmentDetails.service} was not accepted. Please book another slot.`,
  };

  if (customerMessages[newStatus]) {
    await createNotification({
      userId: appointmentDetails.customerId,
      userRole: 'customer',
      type: `appointment_${newStatus}`,
      title: `Appointment ${newStatus.charAt(0).toUpperCase() + newStatus.slice(1)}`,
      message: customerMessages[newStatus],
      relatedId: appointmentId,
      relatedType: 'appointment',
      actionUrl: `/appointments?highlight=${appointmentId}`, // Include appointment ID for highlighting
      actionLabel: 'View Appointment',
    });
  }

  // Notify admin
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: `appointment_${newStatus}`,
    title: `Appointment ${newStatus.charAt(0).toUpperCase() + newStatus.slice(1)}`,
    message: `${userName} ${newStatus} appointment for ${appointmentDetails.customerName} - ${appointmentDetails.service} on ${new Date(appointmentDetails.date).toLocaleDateString()}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });
}

/**
 * Log payment verification
 */
export async function logPaymentVerification(
  userId: string,
  userName: string,
  userEmail: string,
  appointmentId: string,
  status: 'approved' | 'rejected',
  appointmentDetails: {
    customerId: string;
    customerName: string;
    service: string;
    amount: number;
    date: string;
  },
  reason?: string
): Promise<void> {
  // Create audit log
  await createAuditLog({
    userId,
    userRole: 'admin',
    userName,
    userEmail,
    action: `payment_${status}`,
    entityType: 'payment',
    entityId: appointmentId,
    description: `${userName} ${status} payment for ${appointmentDetails.customerName}'s appointment ${reason ? `- Reason: ${reason}` : ''}`,
    status: 'success',
    metadata: {
      status,
      ...appointmentDetails,
      reason,
    },
  });

  // Create notification for customer with improved messaging
  const title = status === 'approved' 
    ? '✅ Payment Verified!' 
    : '❌ Payment Rejected';
  
  const message = status === 'approved'
    ? `Great news! Your payment of ₱${appointmentDetails.amount.toFixed(2)} for ${appointmentDetails.service} on ${new Date(appointmentDetails.date).toLocaleDateString()} has been verified and approved. Your booking is confirmed!`
    : `Your payment proof for ${appointmentDetails.service} was rejected. ${reason ? `Reason: ${reason}.` : ''} Please upload a new payment proof to confirm your booking.`;

  // Use direct Supabase method to ensure notification is saved to database
  console.log('🚀 Using DIRECT SUPABASE to create customer notification...');
  try {
    await createDirectNotification({
      user_id: appointmentDetails.customerId,
      user_role: 'customer',
      type: `payment_${status}`,
      title,
      message,
      related_id: appointmentId,
      related_type: 'payment',
      action_url: `/appointments?highlight=${appointmentId}`,
      action_label: status === 'approved' ? 'View Booking' : 'Resubmit Payment',
    });
    console.log('✅ Direct Supabase notification sent successfully!');
  } catch (error) {
    console.error('❌ Direct Supabase notification failed:', error);
    // Don't throw - try local backend as fallback
    await createNotification({
      userId: appointmentDetails.customerId,
      userRole: 'customer',
      type: `payment_${status}`,
      title,
      message,
      relatedId: appointmentId,
      relatedType: 'payment',
      actionUrl: `/appointments?highlight=${appointmentId}`,
      actionLabel: status === 'approved' ? 'View Booking' : 'Resubmit Payment',
    });
  }
}

/**
 * Log user login
 */
export async function logUserLogin(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'user_login',
    entityType: 'user',
    entityId: userId,
    description: `${userName} logged in`,
    status: 'success',
  });
}

/**
 * Log user logout
 */
export async function logUserLogout(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'user_logout',
    entityType: 'user',
    entityId: userId,
    description: `${userName} logged out`,
    status: 'success',
  });
}

/**
 * Log user registration
 */
export async function logUserRegistration(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'user_registered',
    entityType: 'user',
    entityId: userId,
    description: `New user ${userName} registered`,
    status: 'success',
  });

  // Notify admin of new registration
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'user_registered',
    title: 'New User Registered',
    message: `${userName} (${userEmail}) has registered as a ${userRole}`,
    relatedId: userId,
    relatedType: 'user',
    actionUrl: '/users',
    actionLabel: 'View Users',
  });
}

/**
 * Log service creation/update
 */
export async function logServiceAction(
  userId: string,
  userName: string,
  userEmail: string,
  action: 'created' | 'updated' | 'deleted',
  serviceId: string,
  serviceName: string,
  details?: any
): Promise<void> {
  await createAuditLog({
    userId,
    userRole: 'admin',
    userName,
    userEmail,
    action: `service_${action}`,
    entityType: 'service',
    entityId: serviceId,
    description: `${userName} ${action} service: ${serviceName}`,
    status: 'success',
    metadata: details,
  });
}

/**
 * Log review submission
 */
export async function logReviewSubmission(
  userId: string,
  userName: string,
  userEmail: string,
  reviewId: string,
  appointmentId: string,
  rating: number,
  barberId: string,
  barberName: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole: 'customer',
    userName,
    userEmail,
    action: 'review_submitted',
    entityType: 'review',
    entityId: reviewId,
    description: `${userName} submitted a ${rating}-star review`,
    status: 'success',
    metadata: {
      appointmentId,
      rating,
      barberId,
      barberName,
    },
  });

  // Notify barber
  await createNotification({
    userId: barberId,
    userRole: 'barber',
    type: 'review_received',
    title: 'New Review Received',
    message: `${userName} rated your service ${rating} stars`,
    relatedId: reviewId,
    relatedType: 'review',
    actionUrl: '/profile',
    actionLabel: 'View Reviews',
  });

  // Notify admin
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'review_submitted',
    title: 'New Review Submitted',
    message: `${userName} left a ${rating}-star review for ${barberName}`,
    relatedId: reviewId,
    relatedType: 'review',
    actionUrl: '/reports',
    actionLabel: 'View Reports',
  });
}

/**
 * Log system settings change
 */
export async function logSettingsChange(
  userId: string,
  userName: string,
  userEmail: string,
  settingName: string,
  oldValue: any,
  newValue: any
): Promise<void> {
  await createAuditLog({
    userId,
    userRole: 'admin',
    userName,
    userEmail,
    action: 'settings_changed',
    entityType: 'settings',
    entityId: settingName,
    description: `${userName} changed ${settingName}`,
    status: 'success',
    metadata: {
      settingName,
      oldValue,
      newValue,
    },
  });
}

/**
 * Log user creation (by admin)
 */
export async function logUserCreated(
  adminId: string,
  adminName: string,
  adminEmail: string,
  newUserId: string,
  newUserName: string,
  newUserEmail: string,
  newUserRole: 'customer' | 'barber' | 'admin'
): Promise<void> {
  await createAuditLog({
    userId: adminId,
    userRole: 'admin',
    userName: adminName,
    userEmail: adminEmail,
    action: 'user_created',
    entityType: 'user',
    entityId: newUserId,
    description: `${adminName} created new ${newUserRole} account for ${newUserName}`,
    status: 'success',
    metadata: {
      newUserName,
      newUserEmail,
      newUserRole,
    },
  });

  // Notify the new user
  await createNotification({
    userId: newUserId,
    userRole: newUserRole,
    type: 'account_created',
    title: 'Account Created',
    message: `Your ${newUserRole} account has been created by ${adminName}. Welcome to Supremo Barber!`,
    relatedId: newUserId,
    relatedType: 'user',
  });
}

/**
 * Log user update
 */
export async function logUserUpdated(
  actorId: string,
  actorName: string,
  actorEmail: string,
  actorRole: 'customer' | 'barber' | 'admin',
  targetUserId: string,
  targetUserName: string,
  changes: Record<string, any>
): Promise<void> {
  await createAuditLog({
    userId: actorId,
    userRole: actorRole,
    userName: actorName,
    userEmail: actorEmail,
    action: 'user_updated',
    entityType: 'user',
    entityId: targetUserId,
    description: `${actorName} updated ${targetUserName}'s profile`,
    status: 'success',
    metadata: {
      targetUserName,
      changes,
    },
  });
}

/**
 * Log user deletion
 */
export async function logUserDeleted(
  adminId: string,
  adminName: string,
  adminEmail: string,
  deletedUserId: string,
  deletedUserName: string,
  deletedUserRole: string
): Promise<void> {
  await createAuditLog({
    userId: adminId,
    userRole: 'admin',
    userName: adminName,
    userEmail: adminEmail,
    action: 'user_deleted',
    entityType: 'user',
    entityId: deletedUserId,
    description: `${adminName} deleted ${deletedUserRole} account: ${deletedUserName}`,
    status: 'warning',
    metadata: {
      deletedUserName,
      deletedUserRole,
    },
  });
}

/**
 * Log user suspension
 */
export async function logUserSuspended(
  adminId: string,
  adminName: string,
  adminEmail: string,
  suspendedUserId: string,
  suspendedUserName: string,
  reason?: string
): Promise<void> {
  await createAuditLog({
    userId: adminId,
    userRole: 'admin',
    userName: adminName,
    userEmail: adminEmail,
    action: 'user_suspended',
    entityType: 'user',
    entityId: suspendedUserId,
    description: `${adminName} suspended ${suspendedUserName}${reason ? ` - Reason: ${reason}` : ''}`,
    status: 'warning',
    metadata: {
      suspendedUserName,
      reason,
    },
  });

  // Notify the suspended user
  await createNotification({
    userId: suspendedUserId,
    userRole: 'customer',
    type: 'account_suspended',
    title: 'Account Suspended',
    message: `Your account has been suspended${reason ? `. Reason: ${reason}` : ''}. Please contact support for assistance.`,
    relatedId: suspendedUserId,
    relatedType: 'user',
  });
}

/**
 * Log user unsuspension
 */
export async function logUserUnsuspended(
  adminId: string,
  adminName: string,
  adminEmail: string,
  unsuspendedUserId: string,
  unsuspendedUserName: string
): Promise<void> {
  await createAuditLog({
    userId: adminId,
    userRole: 'admin',
    userName: adminName,
    userEmail: adminEmail,
    action: 'user_unsuspended',
    entityType: 'user',
    entityId: unsuspendedUserId,
    description: `${adminName} unsuspended ${unsuspendedUserName}`,
    status: 'success',
    metadata: {
      unsuspendedUserName,
    },
  });

  // Notify the unsuspended user
  await createNotification({
    userId: unsuspendedUserId,
    userRole: 'customer',
    type: 'account_unsuspended',
    title: 'Account Restored',
    message: 'Your account has been restored. You can now access all services again.',
    relatedId: unsuspendedUserId,
    relatedType: 'user',
  });
}

/**
 * Log password change
 */
export async function logPasswordChange(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string,
  changedByAdmin: boolean = false,
  adminName?: string
): Promise<void> {
  const description = changedByAdmin && adminName
    ? `${adminName} reset password for ${userName}`
    : `${userName} changed their password`;

  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'password_changed',
    entityType: 'user',
    entityId: userId,
    description,
    status: 'success',
    metadata: {
      changedByAdmin,
      adminName,
    },
  });

  // Notify user about password change
  if (!changedByAdmin) {
    await createNotification({
      userId,
      userRole,
      type: 'password_changed',
      title: 'Password Changed',
      message: 'Your password has been successfully changed. If you didn\'t make this change, please contact support immediately.',
      relatedId: userId,
      relatedType: 'user',
    });
  }
}

/**
 * Log profile update
 */
export async function logProfileUpdate(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string,
  changes: string[]
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'profile_updated',
    entityType: 'user',
    entityId: userId,
    description: `${userName} updated their profile: ${changes.join(', ')}`,
    status: 'success',
    metadata: {
      changes,
    },
  });
}

/**
 * Log avatar upload
 */
export async function logAvatarUpload(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string,
  avatarUrl: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'avatar_uploaded',
    entityType: 'user',
    entityId: userId,
    description: `${userName} uploaded a new profile picture`,
    status: 'success',
    metadata: {
      avatarUrl,
    },
  });
}

/**
 * Log payment proof upload
 */
export async function logPaymentProofUpload(
  userId: string,
  userName: string,
  userEmail: string,
  appointmentId: string,
  proofUrl: string,
  amount: number
): Promise<void> {
  await createAuditLog({
    userId,
    userRole: 'customer',
    userName,
    userEmail,
    action: 'payment_proof_uploaded',
    entityType: 'payment',
    entityId: appointmentId,
    description: `${userName} uploaded payment proof for ₱${amount}`,
    status: 'success',
    metadata: {
      appointmentId,
      proofUrl,
      amount,
    },
  });

  // Notify admin
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'payment_proof_uploaded',
    title: 'Payment Proof Uploaded',
    message: `${userName} uploaded payment proof for ₱${amount}. Please verify.`,
    relatedId: appointmentId,
    relatedType: 'payment',
    actionUrl: '/appointments',
    actionLabel: 'Verify Payment',
  });
}

/**
 * Log appointment reschedule
 */
export async function logAppointmentReschedule(
  userId: string,
  userRole: 'customer' | 'barber' | 'admin',
  userName: string,
  userEmail: string,
  appointmentId: string,
  oldDate: string,
  oldTime: string,
  newDate: string,
  newTime: string,
  customerId: string,
  customerName: string,
  barberId: string,
  service: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'appointment_rescheduled',
    entityType: 'appointment',
    entityId: appointmentId,
    description: `${userName} rescheduled appointment from ${oldDate} ${oldTime} to ${newDate} ${newTime}`,
    status: 'success',
    metadata: {
      oldDate,
      oldTime,
      newDate,
      newTime,
      service,
    },
  });

  // Notify customer
  await createNotification({
    userId: customerId,
    userRole: 'customer',
    type: 'appointment_rescheduled',
    title: 'Appointment Rescheduled',
    message: `Your ${service} appointment has been rescheduled to ${new Date(newDate).toLocaleDateString()} at ${newTime}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: `/appointments?highlight=${appointmentId}`, // Include appointment ID for highlighting
    actionLabel: 'View Appointment',
  });

  // Notify barber
  await createNotification({
    userId: barberId,
    userRole: 'barber',
    type: 'appointment_rescheduled',
    title: 'Appointment Rescheduled',
    message: `${customerName}'s ${service} appointment has been moved to ${new Date(newDate).toLocaleDateString()} at ${newTime}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });
}

/**
 * Log barber creation
 */
export async function logBarberCreated(
  adminId: string,
  adminName: string,
  adminEmail: string,
  barberId: string,
  barberName: string,
  barberEmail: string
): Promise<void> {
  await createAuditLog({
    userId: adminId,
    userRole: 'admin',
    userName: adminName,
    userEmail: adminEmail,
    action: 'barber_created',
    entityType: 'barber',
    entityId: barberId,
    description: `${adminName} added new barber: ${barberName}`,
    status: 'success',
    metadata: {
      barberName,
      barberEmail,
    },
  });

  // Notify all admins
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'barber_created',
    title: 'New Barber Added',
    message: `${adminName} added ${barberName} to the team`,
    relatedId: barberId,
    relatedType: 'barber',
    actionUrl: '/barbers',
    actionLabel: 'View Barbers',
  });
}

/**
 * Log barber update
 */
export async function logBarberUpdated(
  adminId: string,
  adminName: string,
  adminEmail: string,
  barberId: string,
  barberName: string,
  changes: Record<string, any>
): Promise<void> {
  await createAuditLog({
    userId: adminId,
    userRole: 'admin',
    userName: adminName,
    userEmail: adminEmail,
    action: 'barber_updated',
    entityType: 'barber',
    entityId: barberId,
    description: `${adminName} updated barber profile: ${barberName}`,
    status: 'success',
    metadata: {
      barberName,
      changes,
    },
  });
}

/**
 * Log barber deletion
 */
export async function logBarberDeleted(
  adminId: string,
  adminName: string,
  adminEmail: string,
  barberId: string,
  barberName: string
): Promise<void> {
  await createAuditLog({
    userId: adminId,
    userRole: 'admin',
    userName: adminName,
    userEmail: adminEmail,
    action: 'barber_deleted',
    entityType: 'barber',
    entityId: barberId,
    description: `${adminName} removed barber: ${barberName}`,
    status: 'warning',
    metadata: {
      barberName,
    },
  });

  // Notify all admins
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'barber_deleted',
    title: 'Barber Removed',
    message: `${adminName} removed ${barberName} from the team`,
    relatedId: barberId,
    relatedType: 'barber',
    actionUrl: '/barbers',
    actionLabel: 'View Barbers',
  });
}

/**
 * Log report generation
 */
export async function logReportGenerated(
  userId: string,
  userRole: 'admin',
  userName: string,
  userEmail: string,
  reportType: string,
  dateRange: { start: string; end: string },
  format: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'report_generated',
    entityType: 'report',
    entityId: `${reportType}_${Date.now()}`,
    description: `${userName} generated ${reportType} report (${format})`,
    status: 'success',
    metadata: {
      reportType,
      dateRange,
      format,
    },
  });
}

/**
 * Log data export
 */
export async function logDataExport(
  userId: string,
  userRole: 'admin',
  userName: string,
  userEmail: string,
  dataType: string,
  recordCount: number,
  format: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'data_exported',
    entityType: 'export',
    entityId: `${dataType}_${Date.now()}`,
    description: `${userName} exported ${recordCount} ${dataType} records as ${format}`,
    status: 'success',
    metadata: {
      dataType,
      recordCount,
      format,
    },
  });
}

/**
 * Log failed login attempt
 */
export async function logFailedLogin(
  email: string,
  reason: string
): Promise<void> {
  await createAuditLog({
    userId: 'unknown',
    userRole: 'system',
    userName: 'Unknown',
    userEmail: email,
    action: 'login_failed',
    entityType: 'auth',
    entityId: email,
    description: `Failed login attempt for ${email}: ${reason}`,
    status: 'error',
    metadata: {
      reason,
    },
  });
}

/**
 * Log & notify: new device login detected for a customer.
 * Called when a customer passes credential check but their device is NOT trusted.
 * Creates an in-app notification so the customer is informed of the access.
 */
export async function logNewDeviceLogin(
  userId: string,
  userName: string,
  userEmail: string,
  deviceInfo: { userAgent: string; time: string }
): Promise<void> {
  // Audit log
  await createAuditLog({
    userId,
    userRole: 'customer',
    userName,
    userEmail,
    action: 'new_device_login',
    entityType: 'user',
    entityId: userId,
    description: `Login from a new / unrecognised device detected for ${userName}`,
    status: 'warning',
    metadata: deviceInfo,
  });

  // In-app security notification (visible in NotificationCenter)
  await createNotification({
    userId,
    userRole: 'customer',
    type: 'new_device_login',
    title: '🔐 New Device Login',
    message: `Your account was accessed from a new device on ${deviceInfo.time}. If this wasn't you, go to Profile → Security and tap "Sign Out From All Devices" immediately.`,
    relatedId: userId,
    relatedType: 'user',
    actionUrl: '/profile',
    actionLabel: 'Review Security',
  });
}

/**
 * Log & notify: customer signed out from all devices.
 */
export async function logSignOutAllDevices(
  userId: string,
  userName: string,
  userEmail: string
): Promise<void> {
  await createAuditLog({
    userId,
    userRole: 'customer',
    userName,
    userEmail,
    action: 'sign_out_all_devices',
    entityType: 'user',
    entityId: userId,
    description: `${userName} revoked all trusted devices`,
    status: 'success',
  });

  await createNotification({
    userId,
    userRole: 'customer',
    type: 'sign_out_all_devices',
    title: '✅ Signed Out From All Devices',
    message: 'All trusted devices have been revoked. You will be required to complete 2FA verification on your next login from any device.',
    relatedId: userId,
    relatedType: 'user',
  });
}

/**
 * Log & notify: Customer cancelled their own appointment.
 * Notifies admin and barber.
 */
export async function logAppointmentCancelledByCustomer(
  userId: string,
  userName: string,
  userEmail: string,
  appointmentId: string,
  appointmentDetails: {
    service: string;
    barber: string;
    barberId: string;
    date: string;
    time: string;
    reason: string;
  }
): Promise<void> {
  // Audit log
  await createAuditLog({
    userId,
    userRole: 'customer',
    userName,
    userEmail,
    action: 'appointment_cancelled',
    entityType: 'appointment',
    entityId: appointmentId,
    description: `${userName} cancelled appointment for ${appointmentDetails.service} on ${appointmentDetails.date} - Reason: ${appointmentDetails.reason}`,
    status: 'warning',
    metadata: appointmentDetails,
  });

  // Notify admin
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'appointment_cancelled',
    title: '❌ Appointment Cancelled by Customer',
    message: `${userName} cancelled their ${appointmentDetails.service} appointment with ${appointmentDetails.barber} on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time}. Reason: ${appointmentDetails.reason}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });

  // Notify barber
  await createNotification({
    userId: appointmentDetails.barberId,
    userRole: 'barber',
    type: 'appointment_cancelled',
    title: '❌ Appointment Cancelled',
    message: `${userName} cancelled their ${appointmentDetails.service} appointment on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time}. Reason: ${appointmentDetails.reason}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Schedule',
  });

  // Confirmation notification for customer
  await createNotification({
    userId,
    userRole: 'customer',
    type: 'appointment_cancelled',
    title: 'Appointment Cancelled',
    message: `Your ${appointmentDetails.service} appointment on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time} has been cancelled.`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: `/appointments?highlight=${appointmentId}`,
    actionLabel: 'View History',
  });
}

/**
 * Log & notify: Barber cancelled an appointment.
 * Notifies admin and customer.
 */
export async function logAppointmentCancelledByBarber(
  userId: string,
  userName: string,
  userEmail: string,
  appointmentId: string,
  appointmentDetails: {
    service: string;
    customerId: string;
    customerName: string;
    date: string;
    time: string;
    reason: string;
  }
): Promise<void> {
  // Audit log
  await createAuditLog({
    userId,
    userRole: 'barber',
    userName,
    userEmail,
    action: 'appointment_cancelled_by_barber',
    entityType: 'appointment',
    entityId: appointmentId,
    description: `Barber ${userName} cancelled appointment for ${appointmentDetails.customerName} - ${appointmentDetails.service} - Reason: ${appointmentDetails.reason}`,
    status: 'warning',
    metadata: appointmentDetails,
  });

  // Notify admin
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'appointment_cancelled',
    title: '❌ Appointment Cancelled by Barber',
    message: `${userName} cancelled ${appointmentDetails.customerName}'s ${appointmentDetails.service} appointment on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time}. Reason: ${appointmentDetails.reason}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });

  // Notify customer
  await createNotification({
    userId: appointmentDetails.customerId,
    userRole: 'customer',
    type: 'appointment_cancelled',
    title: '❌ Appointment Cancelled by Barber',
    message: `Your ${appointmentDetails.service} appointment on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time} was cancelled by ${userName}. Reason: ${appointmentDetails.reason}. Please book a new appointment.`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: `/appointments?highlight=${appointmentId}`,
    actionLabel: 'Rebook Now',
  });
}

/**
 * Log & notify: Admin cancelled an appointment.
 * Notifies customer and barber.
 */
export async function logAppointmentCancelledByAdmin(
  userId: string,
  userName: string,
  userEmail: string,
  appointmentId: string,
  appointmentDetails: {
    service: string;
    customerId: string;
    customerName: string;
    barberId: string;
    barberName: string;
    date: string;
    time: string;
    reason: string;
  }
): Promise<void> {
  // Audit log
  await createAuditLog({
    userId,
    userRole: 'admin',
    userName,
    userEmail,
    action: 'appointment_cancelled_by_admin',
    entityType: 'appointment',
    entityId: appointmentId,
    description: `Admin ${userName} cancelled appointment for ${appointmentDetails.customerName} - ${appointmentDetails.service} - Reason: ${appointmentDetails.reason}`,
    status: 'warning',
    metadata: appointmentDetails,
  });

  // Notify customer
  await createNotification({
    userId: appointmentDetails.customerId,
    userRole: 'customer',
    type: 'appointment_cancelled',
    title: '❌ Appointment Cancelled by Admin',
    message: `Your ${appointmentDetails.service} appointment with ${appointmentDetails.barberName} on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time} was cancelled by administration. Reason: ${appointmentDetails.reason}. Your payment has been rejected.`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: `/appointments?highlight=${appointmentId}`,
    actionLabel: 'View History',
  });

  // Notify barber
  if (appointmentDetails.barberId) {
    await createNotification({
      userId: appointmentDetails.barberId,
      userRole: 'barber',
      type: 'appointment_cancelled',
      title: '❌ Appointment Cancelled by Admin',
      message: `Admin cancelled ${appointmentDetails.customerName}'s ${appointmentDetails.service} appointment on ${new Date(appointmentDetails.date).toLocaleDateString()} at ${appointmentDetails.time}. Reason: ${appointmentDetails.reason}`,
      relatedId: appointmentId,
      relatedType: 'appointment',
      actionUrl: '/appointments',
      actionLabel: 'View Schedule',
    });
  }
}

/**
 * Log & notify: Barber completed an appointment.
 * Notifies customer and admin.
 */
export async function logAppointmentCompleted(
  userId: string,
  userName: string,
  userEmail: string,
  appointmentId: string,
  appointmentDetails: {
    service: string;
    customerId: string;
    customerName: string;
    date: string;
    time: string;
    price: number;
  }
): Promise<void> {
  // Audit log
  await createAuditLog({
    userId,
    userRole: 'barber',
    userName,
    userEmail,
    action: 'appointment_completed',
    entityType: 'appointment',
    entityId: appointmentId,
    description: `${userName} completed ${appointmentDetails.customerName}'s appointment for ${appointmentDetails.service}`,
    status: 'success',
    metadata: appointmentDetails,
  });

  // Notify customer
  await createNotification({
    userId: appointmentDetails.customerId,
    userRole: 'customer',
    type: 'appointment_completed',
    title: '✅ Appointment Completed',
    message: `Your ${appointmentDetails.service} appointment with ${userName} has been completed. We hope you enjoyed the service! Please leave a review.`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: `/appointments?highlight=${appointmentId}`,
    actionLabel: 'Leave a Review',
  });

  // Notify admin
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'appointment_completed',
    title: 'Appointment Completed',
    message: `${userName} completed ${appointmentDetails.customerName}'s ${appointmentDetails.service} appointment (₱${appointmentDetails.price})`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });
}

/**
 * Log & notify: Customer rescheduled their appointment.
 * Notifies admin and barber.
 */
export async function logAppointmentRescheduledByCustomer(
  userId: string,
  userName: string,
  userEmail: string,
  appointmentId: string,
  appointmentDetails: {
    service: string;
    barber: string;
    barberId: string;
    oldDate: string;
    oldTime: string;
    newDate: string;
    newTime: string;
  }
): Promise<void> {
  // Audit log
  await createAuditLog({
    userId,
    userRole: 'customer',
    userName,
    userEmail,
    action: 'appointment_rescheduled',
    entityType: 'appointment',
    entityId: appointmentId,
    description: `${userName} rescheduled ${appointmentDetails.service} from ${appointmentDetails.oldDate} ${appointmentDetails.oldTime} to ${appointmentDetails.newDate} ${appointmentDetails.newTime}`,
    status: 'success',
    metadata: appointmentDetails,
  });

  // Notify admin
  await createNotification({
    userId: 'admin',
    userRole: 'admin',
    type: 'appointment_rescheduled',
    title: '📅 Appointment Rescheduled',
    message: `${userName} rescheduled their ${appointmentDetails.service} appointment with ${appointmentDetails.barber} from ${new Date(appointmentDetails.oldDate).toLocaleDateString()} to ${new Date(appointmentDetails.newDate).toLocaleDateString()} at ${appointmentDetails.newTime}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Appointments',
  });

  // Notify barber
  await createNotification({
    userId: appointmentDetails.barberId,
    userRole: 'barber',
    type: 'appointment_rescheduled',
    title: '📅 Appointment Rescheduled',
    message: `${userName} rescheduled their ${appointmentDetails.service} appointment from ${new Date(appointmentDetails.oldDate).toLocaleDateString()} ${appointmentDetails.oldTime} to ${new Date(appointmentDetails.newDate).toLocaleDateString()} at ${appointmentDetails.newTime}`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: '/appointments',
    actionLabel: 'View Schedule',
  });

  // Confirmation for customer
  await createNotification({
    userId,
    userRole: 'customer',
    type: 'appointment_rescheduled',
    title: '📅 Appointment Rescheduled',
    message: `Your ${appointmentDetails.service} appointment has been moved to ${new Date(appointmentDetails.newDate).toLocaleDateString()} at ${appointmentDetails.newTime}.`,
    relatedId: appointmentId,
    relatedType: 'appointment',
    actionUrl: `/appointments?highlight=${appointmentId}`,
    actionLabel: 'View Appointment',
  });
}

/**
 * Log & notify: New device login detected. Also alerts admins for security.
 */
export async function logNewDeviceLoginWithAdminAlert(
  userId: string,
  userName: string,
  userEmail: string,
  userRole: 'customer' | 'barber' | 'admin',
  deviceInfo: { userAgent: string; time: string }
): Promise<void> {
  // Audit log
  await createAuditLog({
    userId,
    userRole,
    userName,
    userEmail,
    action: 'new_device_login',
    entityType: 'user',
    entityId: userId,
    description: `Login from a new / unrecognised device detected for ${userName} (${userRole})`,
    status: 'warning',
    metadata: deviceInfo,
  });

  // In-app security notification for the user
  await createNotification({
    userId,
    userRole,
    type: 'new_device_login',
    title: '🔐 New Device Login',
    message: `Your account was accessed from a new device on ${deviceInfo.time}. If this wasn't you, change your password immediately.`,
    relatedId: userId,
    relatedType: 'user',
    actionUrl: '/profile',
    actionLabel: 'Review Security',
  });

  // Alert admins of suspicious login (only for non-admin users)
  if (userRole !== 'admin') {
    await createNotification({
      userId: 'admin',
      userRole: 'admin',
      type: 'security_alert',
      title: '🔐 New Device Login Detected',
      message: `${userName} (${userRole}) logged in from a new device on ${deviceInfo.time}. Email: ${userEmail}`,
      relatedId: userId,
      relatedType: 'user',
      actionUrl: '/users',
      actionLabel: 'View User',
    });
  }
}